[package]
name = "graphics"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[features]
uefi = ["dep:uefi"]

[dependencies]
log = { workspace = true }
uefi = { workspace = true, optional = true, features = ["alloc", "logger", "panic_handler"] }
