[package]
description = "A graphics library for the Polished OS project."
edition = "2024"
license = "Zlib"
name = "polished_graphics"
readme = "./README.md"
repository = "https://github.com/ofluffydev/polished"
version = "0.1.0"

[lib]
crate-type = ["rlib"]

[features]
default = []

[dependencies]
libm = "0.2.15"
log = { workspace = true }
