[package]
description = "A collection of allocators for the Polished project"
edition = "2024"
license = "Zlib"
name = "polished_allocators"
repository = "https://codeberg.org/ofluffydev/polished"
version = "0.2.1"

[dependencies]
spin = { version = "0.9", optional = true }
x86_64.workspace = true

[features]
default = []
spin_lock = ["spin"]
