[package]
description = "Low-level routines for initializing and managing PCI devices on x86 systems."
edition = "2024"
license = "Zlib"
name = "polished_pci"
repository = "https://codeberg.org/ofluffydev/polished"
version = "0.2.1"

[lib]
name = "polished_pci"
path = "src/lib.rs"

[features]
default = ["polished_serial_logging"]
logger_log = ["dep:log"]
polished_serial_logging = ["dep:polished_serial_logging"]

[dependencies]
log = { version = "0.4", optional = true }
polished_serial_logging = { version = "0.1.1", path = "../serial_logging", default-features = false, optional = true }
