[package]
default-run = "workspace-default-package"
edition = "2024"
license = "Zlib"
name = "workspace-default-package"
readme = "./README.md"
repository = "https://github.com/ofluffydev/polished"
version = "0.1.0"

[dependencies]
