[package]
name = "interrupts"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
x86_64 = "0.15.2"
serial_logging = { path = "../serial_logging" }
once_cell = { workspace = true }
scancodes = { path = "../scancodes" }