[package]
description = "Interrupt handling for the Polished OS project."
edition = "2024"
license = "Zlib"
name = "polished_interrupts"
readme = "./README.md"
repository = "https://codeberg.org/ofluffydev/polished"
version = "0.1.1"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
once_cell = { workspace = true }
polished_scancodes = { version = "0.1.0", path = "../scancodes" }
polished_serial_logging = { version = "0.1.0", path = "../serial_logging" }
x86_64 = "0.15.2"
