[package]
edition = "2024"
license = "Zlib"
name = "polished_gdt"
readme = "./README.md"
repository = "https://github.com/ofluffydev/polished"
version = "0.1.0"

[dependencies]
once_cell = { workspace = true }
x86_64 = { workspace = true }
