[package]
name = "polished_gdt"
version = "0.1.0"
edition = "2024"
readme = "./README.md"
license = "Zlib"
repository = "https://github.com/ofluffydev/polished"

[dependencies]
once_cell = { workspace = true }
x86_64 = { workspace = true }
