[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
buddy_system_allocator = "0.11.0"
serial_logging = { path = "../serial_logging" }
elf_loader = { path = "../elf_loader" }
graphics = { path = "../graphics", default-features = false }
