[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
serial_logging = { path = "../serial_logging" }
elf_loader = { path = "../elf_loader" }
graphics = { path = "../graphics", default-features = false }
interrupts = { path = "../interrupts" }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
x86_64 = "0.15.2"
once_cell = {workspace = true}
linked_list_allocator = "0.10.5"
