[package]
name = "polished_scancodes"
version = "0.1.0"
edition = "2024"
readme = "./README.md"
license = "Zlib"
description = "A library for handling and mapping keyboard scancodes in Rust."
repository = "https://github.com/ofluffydev/polished"

[dependencies]
