[package]
description = "A library for handling and mapping keyboard scancodes in Rust."
edition = "2024"
license = "Zlib"
name = "polished_scancodes"
readme = "./README.md"
repository = "https://github.com/ofluffydev/polished"
version = "0.1.0"

[dependencies]
