[package]
description = "Low-level x86 instructions and utilities for Polished OS."
edition = "2024"
license = "Zlib"
name = "polished_x86_commands"
readme = "./README.md"
repository = "https://github.com/ofluffydev/polished"
version = "0.1.0"

[dependencies]
