[package]
description = "Polished VirtIO: A Rust library for VirtIO device emulation and management."
edition = "2024"
license = "Zlib"
name = "polished_virtio"
repository = "https://codeberg.org/ofluffydev/polished"
version = "0.1.0"

[dependencies]
polished_pci = { version = "0.2.1", path = "../pci" }
