[package]
name = "elf_loader"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
uefi = { version = "0.35.0", features = ["alloc", "logger", "panic_handler"] }
files = { path = "../files" }
xmas-elf = "0.10.0"
log = "0.4.27"
