[package]
description = "A UEFI bootloader for the Polished OS project."
edition = "2024"
license = "Zlib"
name = "polished_bootloader"
readme = "./README.md"
repository = "https://github.com/ofluffydev/polished"
version = "0.1.0"

[dependencies]
log = { workspace = true }
polished_elf_loader = { version = "0.1.0", optional = true, path = "../elf_loader", features = [
  "uefi",
] }
polished_files = { version = "0.1.0", path = "../files", optional = true, features = [
  "uefi",
] }
polished_graphics = { version = "0.1.0", path = "../graphics" }
uefi = { version = "0.35.0", optional = true, features = [
  "alloc",
  "global_allocator",
  "logger",
  "panic_handler",
] }

[features]
default = ["uefi"]
uefi = ["dep:uefi", "dep:polished_elf_loader", "dep:polished_files"]
